version: '3.8'

services:
  unzip-bot:
    build: .
    container_name: unzip_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./downloads:/app/downloads
      - ./thumbnails:/app/thumbnails
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
